apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-ebs-pvc
  namespace: dev
  labels:
    app: {{ .Release.Name }}-ebs-pvc
    tier: databases
spec:
  storageClassName: {{ .Release.Name }}-ebs-stc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
